/**
 * V4 correction, PR 1: the header every page shares.
 *
 * The header is generated by an applier that runs *after* the page generators, so the failure mode this
 * suite exists to catch is a generator being re-run without it — which would publish a page with no way
 * off it, silently, while every other test still passed.
 *
 * It is asked of the built site rather than of `chromeHtml`, because a function that returns the right
 * string is not the same claim as seventeen pages carrying it.
 */
import test from "node:test";
import assert from "node:assert/strict";
import * as cheerio from "cheerio";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { NAV, PLAYER_CHIP_ID, chromeHtml, sectionOf } from "../../design/chrome";
import { applyChrome, applyPlayerScript } from "../../update-chrome";
import { renderSite } from "../../render-pages";

const ROOT = path.join(__dirname, "..", "..", "..");
const NOW = new Date("2026-09-17T12:00:00.000Z");

function build(): { dir: string; pages: string[]; cleanup(): void } {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "nextreset-chrome-"));
    const copy = (from: string, to: string) => {
        fs.mkdirSync(to, { recursive: true });
        for (const entry of fs.readdirSync(from, { withFileTypes: true })) {
            const a = path.join(from, entry.name);
            const b = path.join(to, entry.name);
            if (entry.isDirectory()) copy(a, b);
            else fs.copyFileSync(a, b);
        }
    };
    copy(path.join(ROOT, "public"), dir);
    const debug = path.join(dir, "data", "_debug");
    if (fs.existsSync(debug)) fs.rmSync(debug, { recursive: true, force: true });
    renderSite(dir, NOW, ROOT);

    const pages: string[] = [];
    const walk = (at: string) => {
        for (const entry of fs.readdirSync(at, { withFileTypes: true })) {
            const full = path.join(at, entry.name);
            if (entry.isDirectory()) walk(full);
            else if (entry.name.endsWith(".html")) pages.push(path.relative(dir, full).replace(/\\/g, "/"));
        }
    };
    walk(dir);
    return { dir, pages: pages.sort(), cleanup: () => fs.rmSync(dir, { recursive: true, force: true }) };
}

const site = build();
const read = (page: string) => fs.readFileSync(path.join(site.dir, page), "utf8");

test.after(() => site.cleanup());

test("every page carries exactly one shared header", () => {
    assert.equal(site.pages.length, 17, `expected 17 pages, found ${site.pages.length}`);
    for (const page of site.pages) {
        const $ = cheerio.load(read(page));
        assert.equal($("header.chrome").length, 1, `${page} has ${$("header.chrome").length} headers`);
        assert.equal($('nav[aria-label="Site"]').length, 1, `${page}: site navigation is not exactly once`);
    }
});

test("the wordmark is the way home, and is not repeated as a navigation item", () => {
    for (const page of site.pages) {
        const $ = cheerio.load(read(page));
        const brand = $("header.chrome a.chrome-brand");
        assert.equal(brand.length, 1, `${page}: no wordmark link`);
        assert.equal(brand.attr("href"), "/", `${page}: the wordmark does not lead home`);
        assert.equal(brand.text().trim(), "NextReset");
        const labels = $('nav[aria-label="Site"] a').map((_, a) => $(a).text().trim()).get();
        assert.ok(!labels.includes("Home"), `${page}: "Home" is in the nav as well as being the wordmark`);
    }
});

test("the navigation is the same three destinations, in the same order, on every page", () => {
    const wanted = NAV.map(item => `${item.label} ${item.href}`);
    for (const page of site.pages) {
        const $ = cheerio.load(read(page));
        const found = $('nav[aria-label="Site"] a').map((_, a) => `${$(a).text().trim()} ${$(a).attr("href")}`).get();
        assert.deepEqual(found, wanted, `${page}: navigation differs`);
    }
});

test("the header does not repeat the twelve trackers the footer already lists", () => {
    // A second copy of the same twelve links on every page would double this site's internal linking
    // to say nothing new. One link to the grid is the whole point of the "Trackers" item.
    for (const page of site.pages) {
        const $ = cheerio.load(read(page));
        assert.ok($('nav[aria-label="Site"] a').length <= 4, `${page}: the header nav has grown`);
    }
});

test("each page marks its own section, and marks it truthfully", () => {
    for (const page of site.pages) {
        const $ = cheerio.load(read(page));
        const section = sectionOf(page);
        const current = $("header.chrome [aria-current]");

        if (section === "none") {
            assert.equal(current.length, 0, `${page} belongs to no section but marks one current`);
            continue;
        }
        assert.equal(current.length, 1, `${page} marks ${current.length} items current`);

        const href = current.attr("href");
        const value = current.attr("aria-current");
        if (section === "trackers") {
            // A tracker page is *in* Trackers without being the page Trackers links to. Claiming "page"
            // would tell a screen reader this link goes nowhere new, which is not true.
            assert.equal(value, "true", `${page}: a tracker page should mark the section, not the page`);
            assert.equal(href, "/#all-games");
        } else {
            assert.equal(value, "page", `${page}: aria-current should be "page" where the link is this page`);
        }
    }
});

test("the player chip ships empty and hidden, so no page claims a player who may not exist", () => {
    for (const page of site.pages) {
        const html = read(page);
        const $ = cheerio.load(html);
        const chip = $(`#${PLAYER_CHIP_ID}`);
        assert.equal(chip.length, 1, `${page}: expected one player chip, found ${chip.length}`);
        assert.equal(chip.text(), "", `${page}: the served HTML already says something about a player`);
        assert.notEqual(chip.attr("hidden"), undefined, `${page}: the chip is not hidden before script runs`);
        assert.ok(!/\bLVL\b|\bXP\b/.test($("header.chrome").text()), `${page}: the header claims progression in the HTML`);
    }
});

test("every page loads the record the header's chip is filled from", () => {
    for (const page of site.pages) {
        const html = read(page);
        assert.match(html, /src="\/assets\/player\.js(\?v=[0-9a-f]{8})?"/, `${page} does not load player.js`);
        assert.equal((html.match(/assets\/player\.js/g) ?? []).length, 1, `${page} loads player.js more than once`);
    }
});

test("player.js and the header agree on the element they share", () => {
    const source = fs.readFileSync(path.join(ROOT, "public", "assets", "player.js"), "utf8");
    assert.ok(source.includes(`var CHIP_ID = '${PLAYER_CHIP_ID}';`), "player.js looks for a different id than the header writes");
});

test("the arcade is now reachable from the header of every page, not only its footer", () => {
    for (const page of site.pages) {
        const $ = cheerio.load(read(page));
        const arcade = $('header.chrome a[href="/play/"]');
        assert.equal(arcade.length, 1, `${page}: no arcade link in the header`);
        assert.equal(arcade.text().trim(), "Arcade");
    }
});

test("the homepage keeps its two claims about the site, and no other page borrows them", () => {
    for (const page of site.pages) {
        const $ = cheerio.load(read(page));
        const badges = $("header.chrome .trust-badge").length;
        assert.equal(badges, page === "index.html" ? 2 : 0, `${page}: ${badges} trust badges`);
    }
});

test("applying the header twice changes nothing the second time", () => {
    // The applier runs after the page generators and may run again at any time. A second pass that
    // differed from the first would mean a page's committed bytes depend on how often a script was run.
    for (const page of ["index.html", "lol/next-patch/index.html", "404.html", "play/index.html"]) {
        const original = fs.readFileSync(path.join(ROOT, "public", page), "utf8");
        const once = applyPlayerScript(applyChrome(original, page), page);
        const twice = applyPlayerScript(applyChrome(once, page), page);
        assert.equal(twice, once, `${page}: the applier is not idempotent`);
        assert.equal(once, original, `${page}: public/ is out of date — run npm run chrome:apply`);
    }
});

test("the header a page carries is the header the source builds for it", () => {
    for (const page of site.pages) {
        const $ = cheerio.load(read(page));
        const built = cheerio.load(chromeHtml({ section: sectionOf(page), badges: page === "index.html" }));
        assert.equal(
            $("header.chrome").html()?.replace(/\s+/g, " ").trim(),
            built("header.chrome").html()?.replace(/\s+/g, " ").trim(),
            `${page}: the header on the page has drifted from scripts/design/chrome.ts`
        );
    }
});

test("no page kept the header it had before there was a shared one, or a comment describing it", () => {
    // The markup and the words about it have to go together. The applier replaces the element it
    // finds; it cannot know about a comment above it, and a comment naming a component that no longer
    // exists is documentation that lies — which is how the homepage kept saying "Top Bar" above a
    // header that had not been one since PR 1.
    for (const page of site.pages) {
        const html = read(page);
        assert.ok(!/topbar|top bar/i.test(html), `${page} still mentions the pre-V4 topbar`);
    }
});
